### ISSUE TITLE
SynchronousOnlyOperation error

### ISSUE THREAD

**Issue by leomartinez2020** [mxschmitt/python-django-playwright#1]
I tried to run the test, but I got this error message:

`django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async`

I had to add *os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"* to the setup method:

 ```
import os

 def setUpClass(cls):
     super().setUpClass()
     os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
     cls.playwright = sync_playwright().start()
     cls.browser = cls.playwright.chromium.launch()
```

Then I had to change these lines of code:

```
from playwright import sync_playwright
page = self.browser.newPage()
page.waitForSelector('text=Django administration')
```
To:
```
from playwright.sync_api import sync_playwright
page = self.browser.new_page()
page.wait_for_selector('text=Django administration')
```

After those changes everything went smoothly.

**Comment by mxschmitt** [comment]
Thanks! Yeah the code was from a long time ago - are you interested in creating a pull request with the fixes?
